server:
  port: ${PORT}  # Render injeta essa variável; não coloque default

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    # Pode remover a linha abaixo se existir em outro lugar para evitar o warning
    # database-platform: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000   # 1 dia em ms

logging:
  level:
    org.springframework.security: DEBUG
