server:
  port: ${PORT:10000}

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# O seu código está lendo security.jwt.secret (pelos logs)
security:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000

logging:
  level:
    org.springframework.security: DEBUG
