server:
  port: 8082

security:
  jwt:
    secret: "coloque-um-segredo-bem-grande-com-mais-de-32-caracteres-1234567890"
    expiration-ms: 86400000 # 24h

spring:
  datasource:
    url: jdbc:h2:mem:sgdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


